### ISSUE TITLE
Unable to specify header with ',' in value

### ISSUE THREAD

**Issue by rychkov** [umputun/reproxy#100]
I want to add 

Access-Control-Allow-Headers:DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type

but in response I got

Access-Control-Allow-Headers:DNT

if I specify

Access-Control-Allow-Headers:"DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"

I got
Access-Control-Allow-Headers:"DNT

for
Access-Control-Allow-Headers:'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type'

I got
Access-Control-Allow-Headers:'DNT

**Comment by umputun** [comment]
how exactly you specify headers? is it via enviroment? If this is the case I see the root cause [here](https://github.com/umputun/reproxy/blob/master/app/main.go#L36) as `,` used as env separator.

As a workaround, I can suggest passing headers in the command line. For the permanent solution, I'm not sure yet how to address it without breaking compatibility

**Comment by umputun** [comment]
I have figured a quick fix allowing usage of commas inside of the quoted string, i.e. `Access-Control-Allow-Headers:"DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"` will work as expected.

The change in the master. if you run it with a container you could pull it (make sure you use `reproxy:master`). If you need a binary let me know for what platform and I'll add it to this ticket

**Comment by rychkov** [comment]
I use docker compose like this

`services:
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./web:/web
    environment:
      - TZ=America/Chicago
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DOCKER_AUTO=true
      - ASSETS_LOCATION=/web
      - DEBUG=true
      - HEADER=
          BadValueHeader:DST,ugly,other,values,
          X-Frame-Options:SAMEORIGIN,
          X-XSS-Protection:1; mode=block;,
          Content-Security-Policy:default-src 'self'; style-src 'self' 'unsafe-inline';
`

**Comment by rychkov** [comment]
After last update

docker-compose.yml

```
services:
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./web:/web
    environment:
      - TZ=America/Chicago
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DOCKER_AUTO=true
      - ASSETS_LOCATION=/web
      - DEBUG=true
      - HEADER=
          Access-Control-Allow-Origin:*,
          Access-Control-Allow-Methods:*,
          Access-Control-Allow-Credentials:true,
          Access-Control-Allow-Headers:"DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type",
          X-Frame-Options:SAMEORIGIN,
          X-XSS-Protection:1; mode=block;,
          Content-Security-Policy:default-src 'self'; style-src 'self' 'unsafe-inline';

  # automatic destination, will be mapped for ^/svc1/(.*)
  svc1:
    image: ghcr.io/umputun/echo-http
    hostname: svc1
    container_name: svc1
    command: --message="hello world from svc1"


  # automatic destination, will be mapped for ^/svc2/(.*)
  svc2:
    image: ghcr.io/umputun/echo-http
    hostname: svc2
    container_name: svc2
    command: --message="hello world from svc2"

  # explicit destination, routing match defined by lables
  whoami:
    image: 'containous/whoami'
    hostname: whoami
    container_name: whoami
    labels:
      reproxy.server: '*'
      reproxy.route: '^/whoami/(.*)'
      reproxy.dest: '/$$1'
```

GET http://localhost:8080/whoami/test
Accept: application/json

I got response

```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"
...
```

but I want 
`Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type` without " symbols.

**Comment by umputun** [comment]
I have added a cleanup for the trailing and leading dbl quotes, so if you put the whole thing in "" it shoud do what you need

i.e. `"Access-Control-Allow-Headers:DNT,X-CustomHeader,blah"`

**Comment by rychkov** [comment]
umputun/reproxy                      master                                                  7d380a10f75f   22 hours ago    12.5MB

```
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./web:/web
    environment:
      - TZ=America/Chicago
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DOCKER_AUTO=true
      - ASSETS_LOCATION=/web
      - DEBUG=true
      - HEADER=
          Access-Control-Allow-Origin:*,
          Access-Control-Allow-Methods:*,
          Access-Control-Allow-Credentials:true,
          "Access-Control-Allow-Headers:DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type",
```

I got 
```
GET http://localhost:8080/whoami/test

HTTP/1.1 200 OK
"Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"
Access-Control-Allow-Credentials: true
```
Looks like fix not work :(

**Comment by umputun** [comment]
the issue here is extra spaces added due to compose/yml formatting. I have added space's cleanup prior to the actual split, should do it

**Comment by rychkov** [comment]
It's work. Thank you.
