### ISSUE TITLE
Can't delete headers within plugin

### ISSUE THREAD

**Issue by evtatarintsev** [umputun/reproxy#108]
I haven't found how to sanitize headers within plugins.
For example I want to delete X-User, X-Company, X-IsAdmin, etc headers.
Conductor middleware only adds headers received from plugins.
```
for k, vv := range reply.HeadersIn {
	for _, v := range vv {
		r.Header.Add(k, v)
	}
}
for k, vv := range reply.HeadersOut {
	for _, v := range vv {
		w.Header().Add(k, v)
	}
}
```
Is there ability to delete headers or plans to do that.

**Comment by umputun** [comment]
Good question. Removing headers is useful for sure, but I'm not sure what the best way to support it. If you have a clever idea of how to do it, pls share.

The first solution I have in mind is adding the `OverrideHeaders` field to the `lib.Plugin` struct returned by the plugin registration and changing the loop above accordingly, i.e. clear all headers first and fill it with the response. It would force plugins to return all the headers and will be back-compatible with the same "add headers" default behavior as now. 

The alternative solution is to add some `reply.HeadersDel` and handle it in condtuctor. 
 
What do you think?

**Comment by umputun** [comment]
#109 added a pair of OverrideHeaders(In|Out) flags returned as a part of the plugin's `Response` and altered the conductor to respect it. I think it should address the problem with the header's removal as well as headers modifications.

Pls, see if this makes sense to you.

**Comment by evtatarintsev** [comment]
Thanks a lot for resolving this issue! Such plugin's behavior is exactly what I've expected.
