### ISSUE TITLE
Make the universal (multi-architecture) container (amd64 and arm64 at least)

### ISSUE THREAD

**Issue by umputun** [umputun/reproxy#11]
The current container built for x86 only

**Comment by umputun** [comment]
the combination of #18 and [Dockefile migration](https://github.com/umputun/reproxy/commit/a769cc89d5a1b18cc3a2175bb8e484429e586970) to multi-arch images seems to do the trick. The image we publish to ghcr.io/umputun/reproxy:master is multiarch and runs fine (natively) on both x86 and arm64, both tested.

However the automatic build on docker hub still producing a single-arch, x86 image only. I can't find any info about such multiarch build via dockerhub. @bobuk any clue? The plan B is to convert autobuild setup on dockerhub to a plain registry destination and publish images directly the same way we do to ghcr.io

**Comment by umputun** [comment]
converted dockerhub automatic build to a simple repository push.

Both registered have multiarch images

**Comment by bobuk** [comment]
:yes: WD!
