### ISSUE TITLE
Support wildcards in host/server

### ISSUE THREAD

**Issue by alek-sys** [umputun/reproxy#112]
Currently host parameter in a rule can only be a specific hostname (`example.com`) or "any" (`*`). It would be extremely helpful to be able to use regex when matching hostname. E.g. define a rule like `api.*,/(.*),http://api-server:8080/$$1` to send any request from hosts `api.example-uat.com` and `api.example-production.com` to the API server. This allows re-using the same rules when deploying into multiple environments, without parametrising Compose file.

It seems doable, basically all logic is in `discovery.go`, with potentially small negative impact on performance (requires iteration over all matchers). Happy to work on a PR, just curious to know what do you think about the feature?

**Comment by umputun** [comment]
makes sense

**Comment by umputun** [comment]
this was added with #113
