### ISSUE TITLE
An ability to bypass Host header

### ISSUE THREAD

**Issue by ffix** [umputun/reproxy#133]
Hey!

Tried to use reproxy for the first time and got some issues with services like Grafana.
 It looks like Grafana server [doesn't handle X-Forwarded-Host header](https://community.grafana.com/t/origin-not-allowed-messages-after-upgrade-to-8-3-6/60550/12) which is non-standard. But there is no ability in reproxy to bypass Host header like you can do with nginx:
```
proxy_set_header Host $host;
```
It may be implemented using command line flag or we can enable it by default.
What do you think about it?

Thanks!

**Comment by ffix** [comment]
I could try to prepare a patch for that

**Comment by umputun** [comment]
this is the place we call the middleware handling headers https://github.com/umputun/reproxy/blob/master/app/proxy/proxy.go#L134

by default `DropHeaders` is empty, so I'm not sure why it will drop any header.

**Comment by umputun** [comment]
I don't think this directive is about bypassing, but rather setting a new header?

**Comment by umputun** [comment]
i see. yeah, making a param to do this will be nice. I don't want to change the default behavior.

feel free to make a PR, thx

**Comment by simplylizz** [comment]
I need the same. @ffix are you still going to implement this?

**Comment by ffix** [comment]
I tried to fix it by adding a simple CLI argument but have understood that this behavior may vary from one container to another. So, now I am using a patched version of reproxy app but have plans to add a per-container header option.
I don't have the exact date when the fix will be done. Feel free to make a PR if you want.

**Comment by mikelorant** [comment]
@umputun Having this issue open indicates that this hasn't been implemented while it clearly shows the fix has been merged. Should close this as done 😄

**Comment by umputun** [comment]
> @umputun Having this issue open indicates that this hasn't been implemented while it clearly shows the fix has been merged. Should close this as done 😄

closed. usually, I let the person who opened the ticket, close it.
