### ISSUE TITLE
Replace fsouza/go-dockerclient with direct docker api calls

### ISSUE THREAD

**Issue by umputun** [umputun/reproxy#14]
Just an idea - trying to minimize the number of third-party dependencies. The go-dockerclient seems to be a heavy one and brings a lot of transitive dependencies.

All we do with docker is just event listener and container's list. It would be nice to replace  go-dockerclient with internal calls to docker api

**Comment by holykol** [comment]
Seems doable. Can you assign me? @umputun

**Comment by umputun** [comment]
thx, all yours.

Some considerations: the only APIs it uses are `ListContainers` and `AddEventListenerWithOptions` but in fact we need  just `ListContainers`. The fancy event loop here is sort of pointless as we don't care how fast and how accurate the system reacts on new/changed/removed containers. In fact, we even slowing the reaction time down to prevent too frequent update events. As far as I can see, all we need to detect the new "event" is to hit `ListContainers` from time to time, compare the result with the previous one, and emit the event if any different.

The subset of data we care about is also very limited (see `containerInfo`) so, no need to get all the details about active containers.

hope it helps

**Comment by stokito** [comment]
FYI docker has an official SDK but it's much harder to deal with events because its API is too low level.
Events must be processed as fast as possible because if event wasn't consumed by a client then it will be lost.
There is one important types of events: health checks and just for them we may need to consume events.

**Comment by umputun** [comment]
why do we care about health check events?

**Comment by stokito** [comment]
if host is unhealthy then it may be better to return 503

**Comment by umputun** [comment]
well, it is an open question if we want this or not and how this will work with `reproxy.ping`. Maybe it could be an option or default, will see. But regardless, why dw we need to listen for events to detect this health status? Won't be some "get list of all containers" contain the health status?

**Comment by stokito** [comment]
yes, list returns the health status in response and the only advantage of events is that they are sent immidiately. Ping should be sufficient but health checks written bu container authors may be more advanced. At this moment we can just ignore events and use plain list refresh.
