### ISSUE TITLE
page display error in readme.md

### ISSUE THREAD

**Issue by rzv-trsc** [umputun/reproxy#146]
There's a display error in your readme.md file: 
![image](https://user-images.githubusercontent.com/81813605/179546270-ba932216-69a4-4391-a066-2013ad64d9ac.png)

The first two examples (static provider; automatic docker discovery) are truncated. 
May want to correct them. :-) 

Keep up the good work!

**Comment by umputun** [comment]
i have no idea what exactly truncated here. It looks fine to me, md rendered properly on both readme.md as well as on reproxy.io
