### ISSUE TITLE
self proxying with docker 

### ISSUE THREAD

**Issue by bobuk** [umputun/reproxy#16]
Opening more ports on reproxy container leads to voluntary proxying additional routes to  himself on this ports 👎 
```
version: '3.3'
services:
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DEBUG=true
```

Shows this in logs (look at the port 🤷 

```
reproxy    | 2021/04/11 01:07:22.156 [INFO]  {discovery/discovery.go:73 discovery.(*Service).Run} match for docker: * ^/api/reproxy/(.*) http://172.25.0.2:443/$1
```

**Comment by umputun** [comment]
This is an interesting one. After considering some heuristic to detect reproxy container from within the container itself (a surprisingly tricky thing to do) I picked a more explicit solution - added a label `reproxy.enabled` and set it to `false` in reproxy dockerfile. In addition to this particular problem, it gives users more control without overcomplicating the code and the configuration.

This is the commit https://github.com/umputun/reproxy/commit/9462170cd13cf6564117ad9626554080766a4990, pls take a look

**Comment by bobuk** [comment]
👍 WFM
