### ISSUE TITLE
Is there any way to ignore certificate check for ssl destinations?

### ISSUE THREAD

**Issue by paul-nameless** [umputun/reproxy#162]
Here is a config file:
```
example.com:
  - { route: "^/(.*)", dest: "https://10.10.10.10:443/$1" }
```
And sometimes there is a case when destination is self signed certificate and I would like to have ability to ignore certificate check. I see some cases for dev or test purposes.
For now I have another service haproxy, which can ignore ssl check but it would be great to add such option to reproxy.

**Comment by umputun** [comment]
this is not a bad idea, should be easy to do on the top-level, i.e. as cli/env param
