### ISSUE TITLE
Simplify usage (based on the real-life setup)

### ISSUE THREAD

**Issue by umputun** [umputun/reproxy#20]
I have tried to migrate one of my non-trivial configurations hosting multiple docker services with nginx-le proxy in front of this and with several static sites to reproxy. The good news - I was able to do most of it and the final configuration seems to be easier. No need for multiple configuration files (i.e. docker-compose + nginx configs) and generally the final compose readable and make sense. 

However, I've run into some unexpected complexity and most of it was self-induced and hopefully can be addressed with relatively easy changes:

1. Mix of static rules and docker provider doesn't seem to work together. Not sure why, need to investigate
2. All of my destination containers needed  `reproxy.route: /(.*)` and `reproxy.dest: /@1` labels and this pair seems to be a good candidate for a new default
3. In order to allow the current label-less docker discovery I'm going to add a new bool parameter turning it on or off. Not sure which makes more sense as a default.
4. Some containers needed to handle multiple servers, i.e. blah.com and www.blah.com, but currently, only a single server name supported. Should be doable to support multiple servers
5. Attempt to serve fully static content with separate reproxy containers (see #12) worked, but looks a little bit odd. I'm not sure if I like it or maybe prefer some other approach
6. I had to set `LISTEN=0.0.0.0:port` to each reproxy container because the default is localhost:port. From safety/security POV it makes sense, but practically every reproxy container will have to have LISTEN define explicitly. Maybe this is the good thing, not sure
7. Additional reproxy servers (for static content) needed `reproxy.enabled: y` because the container itself sets it to false (see #16). This is logical  (technically speaking) but unexpected and confusing in practice.

**Comment by alexeyten** [comment]
Do you really need assets as a separate entity?

Wouldn't it be easier to use it like a “_proxy_” to folder.

```yaml
srv.example.com:
  - {route: "^/api/svc2/(.*)", dest: "http://127.0.0.2:8080/blah2/$1/abc"}
  - {route: "/images/", dest: "/site/images/"}
  - {route: "/styles/", dest: "/site/css/"}
```
or
```yaml
srv.example.com:
  - {route: "^/api/svc2/(.*)", dest: "http://127.0.0.2:8080/blah2/$1/abc"}
  - {route: "/images/", static: "/site/images/"}
  - {route: "/styles/", static: "/site/css/"}
```

**Comment by umputun** [comment]
this is a different use case. The current implementation is a "catch-all" static server intended to serve a single set of static assets per reproxy instance and the intended use case is a bunch of APIs plus a frontend.

The idea to treat non-uri dest as the file server target feels tricky and potentially confusing. Adding static elements is better, but still odd and limited. I mean, I don't see many practical use cases like this, i.e. multiple different static locations for a single host. However, I can think of a much more common use case not covered by this proposal - a single static destination per server

**Comment by umputun** [comment]
1,2,3 and 4 were resolved

**Comment by umputun** [comment]
7 addressed as well by changing docker default discovery, see https://github.com/umputun/reproxy/commit/06a6d595b384e935f2b702bc882ea7666646e364 for more details

**Comment by umputun** [comment]
I think I can live with the explicit LISTEN=0.0.0.0:port. Item 6 (static content servers) still bothers me, but I don't have a better solution yet. @bobuk proposed to extract all static server functionality into a separate target (binary & container) however I'm not sure if I like this idea as it seems to add some additional complexity from the user's point of view.

@alexeyten proposal about the route-level static server is probably too much but we can think about the server-level static server.

Anyway, going to close this one and if we decide to go either route with static server improvement, will open a new ticket
