### ISSUE TITLE
MacOS binary name since 1.2.0 is wrong

### ISSUE THREAD

**Issue by paskal** [umputun/reproxy#208]
<img width="909" alt="image" src="https://github.com/user-attachments/assets/102da76d-ca4a-43be-93bb-b4604d73989d">
vs
<img width="921" alt="image" src="https://github.com/user-attachments/assets/239f528c-30b2-4b01-aace-f1626363a774">

I'll fix it.

**Comment by paskal** [comment]
@umputun could you please fix it? I don't have write permissions for this repo.

This line has to be replaced:

https://github.com/umputun/reproxy/blob/92bd22877ba44f9767ddbda870202f7898773820/.goreleaser.yml#L24

Before:

```
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
```

After:

```
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ if eq .Os \"darwin\" }}macos{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}"
```

**Comment by umputun** [comment]
fixed in https://github.com/umputun/reproxy/commit/0c14b976aa02b22f6f8d0288a9117616950a69fc
