### ISSUE TITLE
Replace pkg/errors with stdlib errors

### ISSUE THREAD

**Issue by vgarvardt** [umputun/reproxy#29]
Really nice project.

I have an idea on a small potential code improvement but wanted to get a feedback before implementing it and submitting a PR.

I noticed that the project uses `github.com/pkg/errors` for wrapping errors while this functionality is available [in stdlib since Go 1.13](https://golang.org/doc/go1.13#error_wrapping).

Long story short: `github.com/pkg/errors.Wrap(err, "something went wrong")` can be replaced with stdlib `fmt.Errorf("something went wrong: %w", err)` and `errors.Unwrap`, `errors.Is` or `errors.As` for different unwrap purpose.

The change should not affect end-user experience, but may allow to reduce 3rd-party dependencies in favour of stdlib functionality.

**Comment by umputun** [comment]
sure, fine with me. Usage of pkg/errors is some kind of old habit from pre 1.13 day ;)
