### ISSUE TITLE
Make a decent reproxy.io website

### ISSUE THREAD

**Issue by umputun** [umputun/reproxy#3]
Can be on github pages. For now, a relatively simple (but not too ugly) single page will do

**Comment by akoppela** [comment]
What should be done?

**Comment by umputun** [comment]
I have no idea, maybe even the current one will do. But I had in mind a typical application site with documentation, examples and so on

**Comment by akoppela** [comment]
I see. So it's more of an explorational task to suggest something.

**Comment by akoppela** [comment]
Page source of [the page] shows that there is `header` element with font links, but [source code] does not have `header` element. How does it get there?

[the page]: https://reproxy.io/
[source code]: https://github.com/umputun/reproxy/blob/master/docs/index.html

**Comment by akoppela** [comment]
The source code of the website has few issues with HTML sctructure:

- Closing `</ul>` tag is missing.
- `html`, `head` and `body` tags are missing.

Would you like me to submit a fix for that?

**Comment by umputun** [comment]
committed the html, pls submit PR, thx

**Comment by stokito** [comment]
Please make a small 5 minutes video with a basic demo and put in on front page. And put it to tiktok for millennials :)

**Comment by akoppela** [comment]
Readme can be used for the website.

**Comment by akellbl4** [comment]
@umputun looks like the site is decent enough for closing this issue :)

**Comment by umputun** [comment]
agree, thx
