### ISSUE TITLE
Metrics exposing

### ISSUE THREAD

**Issue by vdimir** [umputun/reproxy#35]
Hi there!

Is there any plans to expose metrics such as RPS, timings in some format?

**Comment by umputun** [comment]
hi. Sure, this would be nice and helpful and if you want to deal with this - all yours. Probably we should expose metrics in Prometheus-friendly way

**Comment by umputun** [comment]
I have created basic support for management API on a separate port exposing `/prometheus` with a few metrics. 

Pls take a look. I'll appreciate recommendations/ideas/fixes, especially in this particular area, because this is my first attempt to integrate such metrics into an application.

**Comment by umputun** [comment]
ok, this is horrifying how much dependencies the standard prometheus go library brings :( I don't want it in our codebase. Will try some lightweight alternative. So far found this one https://github.com/VictoriaMetrics/metrics

If I can't find a working and lightweight alternative will probably drop this support.

**Comment by psvmcc** [comment]
Is it possible to change Prometheus metrics path from /prometheus to /metrics, or create flag(option) for set it?

**Comment by umputun** [comment]
I did it already a few days ago https://github.com/umputun/reproxy/blob/master/app/mgmt/server.go#L40
