### ISSUE TITLE
Allow customization of all timeouts

### ISSUE THREAD

**Issue by umputun** [umputun/reproxy#5]
Currently, timeouts for both server itself as well as for client transport are hardcoded. It will be nice to externalise all of this

**Comment by bobuk** [comment]
don't forget to make a possibility to set timeouts as unlimited (for long-polling, SSE or websockets f.e.)

**Comment by umputun** [comment]
Added timeouts customization. @bobuk - as far as I understand 0 means unlimited, at least for all timeouts I have checked.
