### ISSUE TITLE
Cache and Expires by Media Type

### ISSUE THREAD

**Issue by grayru** [umputun/reproxy#58]
ASSETS_CACHE now sets only a Cache-control header for all static assets — images, CSS, scripts, and HTML. 
It would be useful at least to have an option to exclude HTML from the cache.

More obvious way - to add Expires header and an option to set it by MediaType. 

I see index HTML pages served from the browser cache in the current configuration even after Hugo's rebuild - because max-age from Cache-control yet to be expired.

**Comment by umputun** [comment]
now you can set different `max-age` for different mime types. For example to set 72h default and 5m for HTML, and 2h for png you can do `ASSETS_CACHE=72h,text/html:5m,image/png:2h`

**Comment by grayru** [comment]
Thanks, but is it still to be released or is it live already?

**Comment by umputun** [comment]
Every commit to the master generates `:master` image automatically. You can test it by changing `umputun/repoxy` image to `umputun/reproxy:master` in your compose

**Comment by grayru** [comment]
Yes, it works now.
