### ISSUE TITLE
Content of X-Forwarded-Host header seems unexpected

### ISSUE THREAD

**Issue by avbasov** [umputun/reproxy#67]
According to [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host), **X-Forwarded-Host** is used for identifying the original host requested by the client, but **reproxy** puts upstream host there. It breaks some third-party applications, that rely on the header for generating URLs.
I know there is no standard for the header, but could **reproxy** use **X-Forwarded-Host** in the way the most of the Internet does?

**Comment by umputun** [comment]
it has `X-Origin-Host` with the original host. Do you expect `X-Forwarded-Host` to have the same value?

btw, you can easily see all headers by doing `curl https://echo.umputun.com`

**Comment by umputun** [comment]
should be fixed in master

**Comment by avbasov** [comment]
Thank you very much for all your work
