### ISSUE TITLE
File event tests may occasionally fail

### ISSUE THREAD

**Issue by stephank** [umputun/reproxy#77]
It looks like certain tests that rely on short timings may occasionally fail. This is coming from downstream NixOS CI, and in this case on macOS: https://hydra.nixos.org/build/143298376/log

But I was unable to reproduce this locally on macOS, either in a normal build or in a build using Nix. I'm guessing it's a matter of tight tolerances and busy CI machine, maybe?

Do you think it's safe to ignore these failures?

**Comment by umputun** [comment]
I'll try to locate a slow box to reproduce it and will adjust timeouts acodrignly

**Comment by umputun** [comment]
nop, still not reproducible. Tried on the smallest box in AWS with the slowest HDD

I have adjusted the test from your log to be less demanding, give it a try and see if it worked.

**Comment by umputun** [comment]
@stephank did it work?

**Comment by stephank** [comment]
Still getting mixed results, see also the discussion in: https://github.com/NixOS/nixpkgs/pull/123579

Several people report `TestFile_Events_BusyListener` also failing, which has similar timeouts. But more interesting is that Nix CI also still fails `TestFile_Events` on macOS only, with the new 0.6.0 release: https://hydra.nixos.org/build/143427730/log

I can run the tests on a loop on both macOS and Linux, and don't see the issue. So, not yet sure what to make of it. 😕

**Comment by umputun** [comment]
not sure what the problem with NixOS CI but if you build tagged versions and not the master, I don't see much value in running tests on your side because we already do it in github's actions ci.

**Comment by stephank** [comment]
I created a PR downstream to disable the failing tests. Still, I find it really strange we so consistently see these fail on macOS. 😕

I think, one of the benefits of running tests is to catch any issues in toolchain differences between GitHub Actions and Nix builds.

**Comment by umputun** [comment]
Personally, I don't see much value in those tests as my primary dev workstation is macOS (both intel and m1). Those tests run a lot of time as a part of the regular dev process.

**Comment by umputun** [comment]
I have tried to see how this test can even fail. there are 3 possibilities I can think of:

- extremely slow IO in the testing environment for macos. It should be **really** slow to write a few bytes in 300ms
- some odd limation around temporary files
- incorrect/incosistent clock. 

I still think the issue is not the real but rather some artifact of Nix CI macos. However, if you still want to run all the tests and just skip this one I can do it based on some unique env key defined by Nix CI. Probably you already have some, so let me know what the env and if you want me to skip this test.

**Comment by stephank** [comment]
I agree, it's probably something strange. Just wish I had more options to debug it.

I think an env var would just be arbitrary? We're doing simple replacement to disable the specific tests now, which is good enough, imho: https://github.com/NixOS/nixpkgs/pull/124060/files

I don't mind if we close this at this point. Think we've given it plenty of thought. Thanks for taking the time to help resolve this. 🙂
