### ISSUE TITLE
Request for PGP-signature file of checksums.txt in release folder

### ISSUE THREAD

**Issue by chakmidlot** [umputun/reproxy#95]

**Comment by umputun** [comment]
any details, like why this even needed?

**Comment by chakmidlot** [comment]
For authenticity verification

**Comment by umputun** [comment]
well, I get the technical part of this but still don't understand why this even needed. One downloads binaries from the github and also downloaded the checksum file. Is the concern around a possibility of MITM and it somehow got modified in the transfer (over https)?

I don't mind adding singing complexity into the release automation but want to make sure it solves a real problem.

**Comment by chakmidlot** [comment]
I think about a case if somebody replaces your binaries or creates a new release on your behalf on GitHub.
Not sure if it can be the case for GitHub files distribution. Or it's more for self-hosted website or less trusted file storage.

I think about the case happened to Linux Mint 6 years ago when hackers got access to Mint's WordPress and replaced the image: https://nakedsecurity.sophos.com/2016/02/22/worlds-biggest-linux-distro-infected-with-malware/

**Comment by umputun** [comment]
okay, added to the release pipeline. The next release will include checksums.gpg file

**Comment by chakmidlot** [comment]
Cool, thanks
